# Generated by Django 3.1 on 2020-08-08 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_loan', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='approvals',
            new_name='Approval',
        ),
    ]
