# Generated by Django 3.0.8 on 2020-07-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200727_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='url_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
