# Generated by Django 3.0.8 on 2020-07-27 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iris', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IrisResults',
            new_name='IrisResult',
        ),
    ]
